# github actions help: https://git.io/JvXDl
name: "build"

on:
  push:
    #branches: [ master_ ]
  pull_request:
    # The branches below must be a subset of the branches above
    #branches: [ master ]
  schedule:
    # 5.35am GMT = 1.35pm WST
    - cron: '01 5 * * *'

jobs:
  info:
    name: machine info
    runs-on: windows-latest
    steps:
    - name: dotnet info
      run: dotnet --info

  build:
    name: build, test, and analyse
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: true
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: checkout
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
      
    # building via msbuild (as used by VS) instead of dotnet because Wix v3 lacks dotnet support
    # - https://github.com/wixtoolset/issues/issues/5627
    
    # setup latest msbuild (v17.1 at time of writing)
    # - https://github.com/marketplace/actions/setup-msbuild
    - name: add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: clean
      run: msbuild ./ClrVpin.sln -t:clean -p:Configuration=Release -m
    - name: restore
      run: msbuild ./ClrVpin.sln -t:restore -p:Configuration=Release -m
    - name: build
      run: msbuild ./ClrVpin.sln -t:build -p:Configuration=Release -p:UseSharedCompilation=false -m    
    - name: tests
      # unfortunately need to specify individual folders/projects instead of the solution file because of WiX v3 compatibility
      run: dotnet test ClrVpin.tests --no-restore && dotnet test Utils.tests --no-restore

    - name: installer artifact
      uses: actions/upload-artifact@v3
      with:
        name: installer
        path: ClrVpin.setup\bin\release\*.msi
        retention-days: 5
          
    - name: perform CodeQL analysis
      uses: github/codeql-action/analyze@v1
  
  release:
    name: tag and release (TBD)
    environment: prod
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: release
        uses: actions/download-artifact@v3
        with:
          name: installer
      - name: show
        run: dir
          
  release_notes:
    name: release notes (TBD)
    runs-on: ubuntu-latest
    steps:
      #- name: release
      #  uses: actions/download-artifact@v3
      # with:
      #    name: installer
      - name: show
        env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $EVENT_CONTEXT
          
          
    
