# github actions help: https://git.io/JvXDl
name: "CI build"

on:
  push:
    #branches: [ master_ ]
  #pull_request:
    # The branches below must be a subset of the branches above
    #branches: [ master ]
  schedule:
    # 5.01am GMT = 1.01pm WST
    - cron: '01 5 * * *'

jobs:
  info:
    name: info
    runs-on: ubuntu-latest
    steps:
    - name: directory
      run: dir -R
    - name: dotnet
      run: dotnet --info
    - name: git context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo expand above env variable        

  build:
    name: build, test, analyse, artifact
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: checkout
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: analysis setup (master and tag only)
      #if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      if: false
      uses: github/codeql-action/init@v1
      with:
        languages: 'csharp'
      
    # building via msbuild (as used by VS) instead of dotnet because Wix v3 lacks dotnet support
    # - https://github.com/wixtoolset/issues/issues/5627
    # - setup latest msbuild (v17.1 at time of writing), refer https://github.com/marketplace/actions/setup-msbuild
    - name: add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    #- name: clean
    #  run: msbuild ./ClrVpin.sln -t:clean -p:Configuration=Release -m
    #- name: restore
    #  run: msbuild ./ClrVpin.sln -t:restore -p:Configuration=Release -m
    - name: build
      run: msbuild ./ClrVpin.sln -t:restore,build -p:Configuration=Release -p:UseSharedCompilation=false -m    
    - name: tests
      # unfortunately need to specify individual folders/projects instead of the solution file because of WiX v3 compatibility
      run: dotnet test ClrVpin.tests --no-restore && dotnet test Utils.tests --no-restore

    - name: upload artifact (tag only)
      # only create artifactgs for tagged versions
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v3
      with:
        name: installer
        path: ClrVpin.setup\bin\release\*.msi
        retention-days: 5

    - name: analysis (master and tag only)
      # codeQL is rather slow, so only perform for master commits and tagging
      #if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      if: false
      uses: github/codeql-action/analyze@v1
          
  release:
    name: release (tag only)
    if: startsWith(github.ref, 'refs/tags/')      
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write # required for release notes only
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: installer
      - name: unzip artifacts
        run: |
          dir
          tar -xf installer.zip
          dir
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: ClrVpin.Setup.msi
          draft: true
          generateReleaseNotes: true
          body: blah
          
                    
